global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "blackbox_https"
    metrics_path: /probe
    params:
      module: [https_ssl]
    static_configs:
      - targets:
          - https://squadcore.tech
          - https://wilsonnascimentocosta.com.br
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
